# Generated by Django 2.2.4 on 2020-06-16 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='none')),
                ('opening_statement', models.TextField(default='none')),
                ('did_you_miss', models.TextField(default='none')),
                ('in_this_post', models.TextField(default='none')),
                ('headline_1', models.TextField(default='none')),
                ('headline_2', models.TextField(default='none')),
                ('headline_3', models.TextField(default='none')),
                ('headline_4', models.TextField(default='none')),
                ('link_1', models.TextField(default='none')),
                ('content', models.TextField(default='none')),
                ('tweet_quote', models.TextField(default='none')),
                ('more_gist', models.TextField(default='none')),
                ('link_2', models.TextField(default='none')),
                ('games', models.TextField(default='none')),
                ('encourage_comeback', models.TextField(default='none')),
                ('subscription_talk', models.TextField(default='none')),
            ],
        ),
    ]
