# Generated by Django 2.2.4 on 2020-06-17 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200616_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='keyphrase',
            field=models.TextField(default='none'),
        ),
    ]
