# Generated by Django 2.2.4 on 2020-06-17 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_article_keyphrase'),
    ]

    operations = [
        migrations.AddField(
            model_name='didyoumiss',
            name='link',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='linkfour',
            name='title',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='linkone',
            name='title',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='linkthree',
            name='title',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='linktwo',
            name='title',
            field=models.TextField(default='none'),
        ),
    ]
