# Generated by Django 2.2.4 on 2020-06-22 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200617_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='questions',
            field=models.TextField(default='none'),
        ),
    ]
